version: '3.7'
services:
  webapp:
    build: ./
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASS: admin
    depends_on:
      - db
    volumes:
      - data:/data
    ports:
      - 5000:5000
  db:
    image: postgres:11.5
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: football-teams
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
volumes:
  db-data:
  data: